### ISSUE TITLE
Doppler shift animation and panel does not include negative shift

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#273]
Hi Cédric:

On the latest V2.3.3 Dev jSolEx, I noticed when doing panels (see attached), the the doppler shift only shows the positive shift. I'm pretty sure that the shift normally should include both approaching and receding objects (plasma in this case).  So, a panel showing frames from 0 to 1.1 angstrom, I think should instead be showing -1.1 to 1.1 angstroms, centered around zero. And I imagine the sweep shouldn't go so far out into the wings as to reach the continuum - but that's a judgment call.

Things like filaments and other eruptions have both rising and falling areas, so I would expect a doppler animation to show both.

Fabulous work on this excellent project - I've been using it most of the day, after making scans this morning.

Steve
![Sun_090603_20240525_redshift-2](https://github.com/melix/astro4j/assets/28873616/2392c948-0e33-4d15-adbc-34329e9a33ec)

**Comment by melix** [comment]
Hi Steve!

In fact this is not fully accurate: the animations show shifts from -1 to 1 A, but the _panels_ only show from 0 to 1 (or -1 to 0 depending on where the maximum shift was detected). In addition, in animations there's interpolation between frames, where there's nothing for panels. The reason I've done this this way is that otherwise the panels were fairly large (twice their current size).

I can add an option to tell if you prefer to have the full range though.

**Comment by stefanoaz** [comment]
Thanks for the additional detail Cédric. I think it would be nice to have a button allowing the full range to be a non-default option. It would be educational at least. I wouldn't call it a high priority, but would be nice to have.

Thanks for the work you have put into this.

Steve

**Comment by melix** [comment]
This is shipped into 2.3.3, enjoy!

**Comment by stefanoaz** [comment]
Thanks Cédric, I just downloaded it.

Cheers,

Steve
