### ISSUE TITLE
Dark lane artifact in reconsttructed image from otherwise normal .ser file

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#334]
I noticed in the last 2 version (currently 2.5.2), many of my .ser file when processed has a dark band in the reconstructed image. I re-analyzed the exact same file with INIT and got typical reconstructed image as expected. I attached one such result image processed by JSol'ex, and the .ser file and related data can be found in my shared folder:

https://drive.google.com/drive/folders/1peKBQRxkCbCpqkaDw9_pGZdOUB4dBbQV?usp=sharing

![08_57_17_20240628_recon_15_00](https://github.com/melix/astro4j/assets/160078210/dc8df58d-c979-448f-b96e-13ed21e2d6cb)

**Comment by melix** [comment]
The issue is that there are simply no 15 pixels to use when reconstructing the image. This can be seen in the spectrum debugger:

![image](https://github.com/melix/astro4j/assets/316357/4840349b-2eb9-4c42-bf09-b3ae9cc77f80)

One option is to use -15 pixels in your case, instead of 15. I should add a warning in this case and reduce to the maximum usable shift.

Note also that your gain is probably too high, you are loosing a significant part of the dynamics.

**Comment by stefanoaz** [comment]
Hi Cèdric:

I often use negative pixel shifts to avoid the banding in the continuum. But it wouldn't be a good idea to restrict the pixel shifting to 15, for those with 2µm pixels. 15 pixels is too small an offset from H-alpha to produce a continuum free of H-alpha details. If I see a single band or a bright section of the disk near the edge in the continuum, I immediately look at the pixel offset and adjust it - in the negative direction if necessary.

steve

**Comment by melix** [comment]
Not sure what this comment means. You can adjust the continuum shift as needed. It is not limited to 15 or -15.

**Comment by stefanoaz** [comment]
You were saying "reduce to the maximum usable shift." I was concerned that you might go back to the 15 pixels of INTI. But I now suspect you meant that jSolEx would determine this from the spectral frame average and make a software-based decision, which seems like a good idea.

steve
