### ISSUE TITLE
Line misdetection, jumping between two lines

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#343]
I scanned around the Magnesium region, and observed that seemingly randomly, the equation following the spectral line, curves over to another line. I have the debug images checkbox checked, hence I have the following images at hand.

JSol'Ex version: 2.5.0
The raw ser videos are 17-20 GiB, with PIPP I could perhaps cut away the dark lead in and tail, but still north of 10 GiB.

Correct detection:

![image](https://github.com/melix/astro4j/assets/21062213/95737755-5e27-4cf2-b2c8-86f53cd779c8)

Bad detections:

![image](https://github.com/melix/astro4j/assets/21062213/62d27bb9-7854-47c7-bc69-f1925276c931)

![image](https://github.com/melix/astro4j/assets/21062213/592e643f-0114-412a-9fca-52a2eff56543)

INTI crashes with the same videos, at around the _raws_, which then look weird (as expected, horizontal bars, as the equation runs through dark absorption lines and bright continuum regions).

---

With PIPP, I cropped the videos to the upper half. One detection was successful:
![image](https://github.com/melix/astro4j/assets/21062213/093ba20b-23d4-4760-b9d7-b73e37b6859e)

The other one remained weird:
![image](https://github.com/melix/astro4j/assets/21062213/85245489-0290-4b6e-a1c6-d0495d620e45)

---

The log says a mercury line was detected with binning... I don't use binning, and I have set it nowhere, it's binning 1. Nota bene, this log below comes from the PIPPed ser videos, that don't have the camera settings next to them.

`19:03:22.667 [INFO] Output directory set to G:\2024-07-06\Sun-Mg\pipp_20240706_190025
19:03:22.678 [INFO] File 2024-07-06-0909_4-Sun-Mg_pipp.ser
19:04:12.057 [INFO] Dimensions of raw image determined : 3696x10031
19:04:12.079 [INFO] Processing will require approximatively 4.35GB of disk space
19:04:12.869 [INFO] Detected spectral line Mercury (e) with binning 2 (for pixel size 2.00µm)
19:04:12.870 [INFO] Starting reconstruction...
19:04:12.870 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -2.4964788775872423E-8
   - b = 1.551143855514092E-4
   - c = -0.24450249855496775
   - d = 119.51547979181157
19:05:52.649 [INFO] Reconstruction done. Generating images...
`

This log comes from the original ser, with a failed detection

`15:02:58.387 [INFO] Output directory set to D:\2024-07-06\Sun-Mg
15:02:58.395 [INFO] File 2024-07-06-0909_4-Sun-Mg.ser
15:02:58.407 [INFO] Found Sharpcap metadata. Camera ZWO ASI678MM Binning 1
15:05:24.531 [INFO] Dimensions of raw image determined : 3696x10031
15:05:24.551 [INFO] Processing will require approximatively 4.35GB of disk space
15:05:24.928 [INFO] Detected spectral line H-alpha with binning 1 (for pixel size 2.00µm)
15:05:24.929 [INFO] Starting reconstruction...
15:05:24.929 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -2.596453989901044E-8
   - b = 1.589978540622785E-4
   - c = -0.24745246502867957
   - d = 184.52403840683246
`

**Comment by melix** [comment]
Thanks for the bug report. This is not an easy fix. The detection algorithm assumes a _single_ line which is darker than the others. In your case, there are multiple dark lines, and sometimes the points with the lowest intensity shift from one line to the other. I have already added some filtering in place to filter out "bad" sample points, but in such a situation, the algorithm won't work well. If possible, try to reduce the cropping window so that it only contains a single darker line.

**Comment by vnp85** [comment]
Thank you for looking into it. Would it be possible for the line detection
to come up with competing solutions, assuming the most linear one as the
likely solution?

In case of the line suddenly going downwards it is quite surprising.

**Comment by melix** [comment]
That's precisely the problem. How do you determine "most linear", when all you have is a set of sample points :)

**Comment by vnp85** [comment]
My thinking was that we start tracing a line. Then it is not only the
darkness of the next candidate point that matters but the pixel distance
from the last point, something like:

pointViability = deltaDarkness * ( verticalDistanceFromLastSample ^
somePower )

thus if the vertical distance is really high for one point but not for a
less dark other point, then we know which one is the correct one

Just thinking aloud. I'm recording and processing SHG as we speak, and your
software is of great help.

**Comment by melix** [comment]
As I mentioned I already have such measures in place to remove false positives. For example, we're starting with a limited area which is in the center of the cropping window, in order to reduce the noise around the limbs. Then I'm computing the variance of pixels around the average, and filtering out these which are "too far". Then considering more pixels around the whole width, in order to improve precision of the measures. The issue here is really that within the same cropping window, you have different lines which have similar darkness.

**Comment by melix** [comment]
Fixed in 2.6.1 devel version
