### ISSUE TITLE
Request: live view reconstruction from ser file

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#386]
Is it possible to visualize live view reconstruction from a ser file, with ability to zoom, pause and rewind? 

This would be educational and useful to help correlate spectral features with reconstructed images. I use INTI mainly for that feature now.

**Comment by vnp85** [comment]
I think my suggestion fits here: a scrollable reconstruction view, of which the live reconstruction is a subset. 

Scrolling in time of the ser to get to a certain state of the reconstruction. 
This is a printscreen I got from INTI. The use case is to link an event in the spectral view, to the position on the disk. The context was this eruption, rim at 2 o'clock https://sdo.gsfc.nasa.gov/assets/img/browse/2024/07/22/20240722_093500_1024_0094.jpg



![image](https://github.com/user-attachments/assets/2be5e32d-03e7-4b12-a012-2f27c99998c2)

**Comment by melix** [comment]
Does INTI has scrollable reconstruction? I missed that. JSol'Ex has live reconstruction, but for small files it's probably too fast to notice. On larger (>1GB) files it's definitely more visible.

**Comment by vnp85** [comment]
For INTI, I kept my finger on printscreen to get this exact moment. It has an "advanced option" hidden under a collapsed submenu

![image](https://github.com/user-attachments/assets/5ce1fdae-4d0c-42a2-8e61-584598201da7)

**Comment by melix** [comment]
I know that there's reconstruction live view, but I don't think you can pause or rewind, can you?

**Comment by vnp85** [comment]
INTI: If there is such an option to pause, rewind, scroll manually etc, I most certainly didn't find it. Hence my addition to this feature request.

JSol'Ex: I am not sure I ever saw the reconstruction happen in on my screen. I have three PCs in my Ersatz-Obsi, one for recording only, and two for processing. I usually go with batch process, and leave the machine alone: having relatively poor equipment, I try to get lucky by taking several scans, hoping that there would be usable disks among the bad ones.

**Comment by melix** [comment]
In JSol'Ex live reconstruction is enabled by default. However it doesn't display the spectrum in parallel, it only shows the disk being reconstructed live. Actually it shows _multiple_ disks reconstructed in parallel (one for each pixel shift):

![Screenshot from 2024-07-23 10-11-45](https://github.com/user-attachments/assets/ce21ff9b-4ac8-4580-931d-5d9ab294732a)

**Comment by smart-underworld** [comment]
I don't see live reconstruction in JSol'ex. That's why I requested the
feature.

I use INTI for this function. As described by others, it is limited in
features but useful nonetheless. My request for the ability to pause,
scroll and zoom is new and would really enhance the value of this view.

**Comment by melix** [comment]
> I don't see live reconstruction in JSol'ex. That's why I requested the feature.

Please explain what you mean by this. If you select either the fast or full process modes, you have the reconstruction, as I have shown in the capture. It may be that it's fast enough that you don't "see" it because it reconstructs too fast, but you should see them.

I understand the feature you want, but I'm confused you're saying that you don't have reconstruction.

**Comment by smart-underworld** [comment]
As you eluded, live reconstruction was probably too fast for me to
recognize that it was live. The value of my proposal is to match the
reconstruction with the spectral view, and the ability to slow down, pause,
rewind to pinpoint exact instances where solar visual features manifest
themselves with the captured spectrum.

**Comment by smart-underworld** [comment]
Ability to synchronously zoom into a spatial region in time with the
spectra would be awesome as well.

**Comment by melix** [comment]
Not everyday that users complain that something is too fast :) Just kidding ;)

**Comment by stefanoaz** [comment]
Cèdric:

One thing to worry about is feature creep. For instance, when I generate Helium images via autodetect (a great feature), a more recent change means that I have to manually delete two images that add very little value to the result - the "direct" emission images versus the subtraction images that have far more contrast. This latest "direct" feature seems to have almost zero value, but does add the work of deleting two "direct" images of questionable value. Does live reconstruction have much value? It's very slow, which is why I always turn it off in INTI. I also don't want those extra files. The raw image is enough to tell me about x/y ratio and tilt. 

steve

**Comment by melix** [comment]
> This request should not be considered as a default mode, but as an introspection tool to zero in on interesting features.

Absolutely, I think it's a great feature for learning and educational purposes. One who wants to learn more about how Sol'Ex works should be able to use the software to understand more. I learnt by writing JSol'Ex, but not everyone should have to do this :D

**Comment by vnp85** [comment]
@stefanoaz From reading the source code, I'd imagine these as options, as you say, maybe not defaults. I don't think they are feature creep.

On the surface level, we have the spectrum explorer window, and the video/ser debugger (it changed its title recently) or the ImageMath scripting  window. All three build on core functionalities that are already there and necessary in JSol'Ex, and are mere user interfaces for them:  spectral line identification, ser playback and line/polynom extraction, reconstruction,  and image operations. 

In a way, it is an extra that the extracted helium line is hidden from the user, as it most certainly needs to be generated like all the other images that are saved onto the disk.

**Comment by melix** [comment]
So, instead of "pause and replay", would something like this work for you? I have a prototype, which I need to make better (there are alignment issues), but using it it feels like it makes redundant the idea of replay.


https://github.com/user-attachments/assets/92bb4523-1165-4ebc-b7ba-da246d9d7395

**Comment by vnp85** [comment]
Rather unexpected, but I like the concept. If you could display the ser frame number (to aid potential frame extraction through AS4 for example), it would be awesome.

**Comment by smart-underworld** [comment]
That's great. Can we zoom in?
