### ISSUE TITLE
Dopplergrams Question

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#420]
I think I am missing something about how the dopplergrams are created and how to interpret them, perhaps even in general, when it is about the Sun. So by convention, blue should be coming towards the viewer and red should be receding.

![image](https://github.com/user-attachments/assets/9456b3bd-377d-43ed-a83b-5253ec823c8a)

However, we see two kinds of shifts: we see shifts of darkness and shifts of light. 

On the disk, does darkness mean receding gas is hiding bluer wavelengths (because from the photosphere's perspective, it is coming closer, it is receding from our perspective). Beyond the disk however, recession shows up as a light source in the red wing instead of the band's center?

![image](https://github.com/user-attachments/assets/4ce1cab2-eee9-4408-bc0c-725e49de7b5a)

**Comment by vnp85** [comment]
If I am right, then this +- 30 px image should be accurate, reflecting a +-70km/s (give or take) radial speed

![image](https://github.com/user-attachments/assets/2c7d9d42-340e-4b80-ae4b-5452aa68ccce)

**Comment by melix** [comment]
I cannot answer this question because I'm not an expert here. I think the interpretation of the spectrum is subject to caution. While for H-alpha, the shifts of the central dark line is certainly due to ejecta of matter, in which case we can compute velocities, I cannot say much for white spots. These are mostly visible in calcium, but sometimes in H-alpha too. In Ha they are most likely due to hot plasma, but in general, I wouldn't dare trying to explain. You may better ask experts like Christian.

**Comment by vnp85** [comment]
Above, both of my images (composed in ms paint, and the disk) are in H alpha, and I restrict my question to dark-feature-moves-off-band on the light disk, and light-feature-moves-off-band beyond the disk, aka prom.

**Comment by melix** [comment]
Again I'm no expert here. I cannot provide physics explanation for white features. A spectrum frame like this captures a particular instant. The dark, off band features can be seen as a Doppler shift of the h-alpha line, and the fact that the features are not straight lines is a realization of the "3d" reconstruction of the ejecta : the velocity is different at different X values. That's what JSol'Ex uses to compute velocities, but it's subject to caution. A filament typically has a much lower velocity, which is why it's not typically visible off-band. So, if a black feature is towards the blue wing, I would tend to think that it's matter coming _towards_ us. But I may be wrong, if indeed it's an absorption phenomenon.

**Comment by vnp85** [comment]
I have the "cube" for this particular instance, 30+1+30 pixel shifts, going through from blue-onBand-red, if you want to check it out, the 2GB file, and the larger ser is the source recording. http://narnia.go.ro/seagate2tb.php?mask=2024-09-13

**Comment by melix** [comment]
I guess I can close this one, right?

**Comment by vnp85** [comment]
Yes, thank you
